# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graph_window(object):
    def setupUi(self, Graph_window):
        Graph_window.setObjectName("Graph_window")
        Graph_window.resize(611, 439)
        self.centralwidget = QtWidgets.QWidget(Graph_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mos_type_label = QtWidgets.QLabel(self.centralwidget)
        self.mos_type_label.setObjectName("mos_type_label")
        self.verticalLayout.addWidget(self.mos_type_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.plot_label = QtWidgets.QLabel(self.centralwidget)
        self.plot_label.setObjectName("plot_label")
        self.verticalLayout.addWidget(self.plot_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.var1_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.var1_comboBox.setObjectName("var1_comboBox")
        self.horizontalLayout.addWidget(self.var1_comboBox)
        self.division_label = QtWidgets.QLabel(self.centralwidget)
        self.division_label.setAlignment(QtCore.Qt.AlignCenter)
        self.division_label.setObjectName("division_label")
        self.horizontalLayout.addWidget(self.division_label)
        self.var2_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.var2_comboBox.setObjectName("var2_comboBox")
        self.horizontalLayout.addWidget(self.var2_comboBox)
        self.gmid_label = QtWidgets.QLabel(self.centralwidget)
        self.gmid_label.setObjectName("gmid_label")
        self.horizontalLayout.addWidget(self.gmid_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.save_all_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_all_pushButton.sizePolicy().hasHeightForWidth())
        self.save_all_pushButton.setSizePolicy(sizePolicy)
        self.save_all_pushButton.setObjectName("save_all_pushButton")
        self.horizontalLayout.addWidget(self.save_all_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.at_label = QtWidgets.QLabel(self.centralwidget)
        self.at_label.setObjectName("at_label")
        self.verticalLayout.addWidget(self.at_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.length_label = QtWidgets.QLabel(self.centralwidget)
        self.length_label.setAlignment(QtCore.Qt.AlignCenter)
        self.length_label.setObjectName("length_label")
        self.horizontalLayout_3.addWidget(self.length_label)
        self.length_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.length_comboBox.setObjectName("length_comboBox")
        self.horizontalLayout_3.addWidget(self.length_comboBox)
        self.VDS_label = QtWidgets.QLabel(self.centralwidget)
        self.VDS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VDS_label.setObjectName("VDS_label")
        self.horizontalLayout_3.addWidget(self.VDS_label)
        self.VDS_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.VDS_comboBox.setObjectName("VDS_comboBox")
        self.horizontalLayout_3.addWidget(self.VDS_comboBox)
        self.VSB_label = QtWidgets.QLabel(self.centralwidget)
        self.VSB_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VSB_label.setObjectName("VSB_label")
        self.horizontalLayout_3.addWidget(self.VSB_label)
        self.VSB_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.VSB_comboBox.setObjectName("VSB_comboBox")
        self.horizontalLayout_3.addWidget(self.VSB_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.plot_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.plot_pushButton.setObjectName("plot_pushButton")
        self.verticalLayout.addWidget(self.plot_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Graph_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Graph_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        Graph_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Graph_window)
        self.statusbar.setObjectName("statusbar")
        Graph_window.setStatusBar(self.statusbar)

        self.retranslateUi(Graph_window)
        QtCore.QMetaObject.connectSlotsByName(Graph_window)

    def retranslateUi(self, Graph_window):
        _translate = QtCore.QCoreApplication.translate
        Graph_window.setWindowTitle(_translate("Graph_window", "Graph Window"))
        self.mos_type_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:14pt;\">MOSFET Type:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Graph_window", "NMOS"))
        self.comboBox.setItemText(1, _translate("Graph_window", "PMOS"))
        self.plot_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:14pt;\">Plot:</span></p></body></html>"))
        self.division_label.setText(_translate("Graph_window", "/"))
        self.gmid_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:12pt;\">vs. g</span><span style=\" font-size:12pt; vertical-align:sub;\">m</span><span style=\" font-size:12pt;\">/I</span><span style=\" font-size:12pt; vertical-align:sub;\">d</span></p></body></html>"))
        self.save_all_pushButton.setText(_translate("Graph_window", "Save All Graphs"))
        self.at_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:14pt;\">At:</span></p></body></html>"))
        self.length_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:12pt;\">Length</span></p></body></html>"))
        self.VDS_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:12pt;\">V</span><span style=\" font-size:12pt; vertical-align:sub;\">DS</span></p></body></html>"))
        self.VSB_label.setText(_translate("Graph_window", "<html><head/><body><p><span style=\" font-size:12pt;\">V</span><span style=\" font-size:12pt; vertical-align:sub;\">SB    </span></p></body></html>"))
        self.plot_pushButton.setText(_translate("Graph_window", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph_window = QtWidgets.QMainWindow()
    ui = Ui_Graph_window()
    ui.setupUi(Graph_window)
    Graph_window.show()
    sys.exit(app.exec_())
