# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(633, 545)
        main_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.generateGmIdCharts = QtWidgets.QWidget()
        self.generateGmIdCharts.setObjectName("generateGmIdCharts")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.generateGmIdCharts)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.model_path_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.model_path_label.setObjectName("model_path_label")
        self.gridLayout_3.addWidget(self.model_path_label, 0, 0, 1, 1)
        self.browseModelbutton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.browseModelbutton.setObjectName("browseModelbutton")
        self.gridLayout_3.addWidget(self.browseModelbutton, 0, 2, 1, 1)
        self.modelPathLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.modelPathLineEdit.setEnabled(True)
        self.modelPathLineEdit.setClearButtonEnabled(False)
        self.modelPathLineEdit.setObjectName("modelPathLineEdit")
        self.gridLayout_3.addWidget(self.modelPathLineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.generateVBSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVBSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVBSlineEdit.setSizePolicy(sizePolicy)
        self.generateVBSlineEdit.setObjectName("generateVBSlineEdit")
        self.gridLayout_4.addWidget(self.generateVBSlineEdit, 2, 1, 1, 1)
        self.temp_lineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.temp_lineEdit.setObjectName("temp_lineEdit")
        self.gridLayout_4.addWidget(self.temp_lineEdit, 5, 1, 1, 1)
        self.generateVDSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVDSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVDSlineEdit.setSizePolicy(sizePolicy)
        self.generateVDSlineEdit.setObjectName("generateVDSlineEdit")
        self.gridLayout_4.addWidget(self.generateVDSlineEdit, 1, 1, 1, 1)
        self.temp_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.gridLayout_4.addWidget(self.temp_label, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.generateVGSLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVGSLineEdit.sizePolicy().hasHeightForWidth())
        self.generateVGSLineEdit.setSizePolicy(sizePolicy)
        self.generateVGSLineEdit.setObjectName("generateVGSLineEdit")
        self.gridLayout_4.addWidget(self.generateVGSLineEdit, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.generateLlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.generateLlineEdit.setObjectName("generateLlineEdit")
        self.gridLayout_4.addWidget(self.generateLlineEdit, 3, 1, 1, 1)
        self.Width_lineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.Width_lineEdit.setObjectName("Width_lineEdit")
        self.gridLayout_4.addWidget(self.Width_lineEdit, 4, 1, 1, 1)
        self.width_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.width_label.setAlignment(QtCore.Qt.AlignCenter)
        self.width_label.setObjectName("width_label")
        self.gridLayout_4.addWidget(self.width_label, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.generatepushButton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.generatepushButton.setObjectName("generatepushButton")
        self.gridLayout_2.addWidget(self.generatepushButton, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.generateGmIdCharts, "")
        self.gmid_graphs = QtWidgets.QWidget()
        self.gmid_graphs.setObjectName("gmid_graphs")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gmid_graphs)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gmid_graphs)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.gmid_graphs)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.gmid_graphs)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.gmid_graphs)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nmos_data_label = QtWidgets.QLabel(self.gmid_graphs)
        self.nmos_data_label.setObjectName("nmos_data_label")
        self.horizontalLayout_7.addWidget(self.nmos_data_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.nmos_data_lineEdit = QtWidgets.QLineEdit(self.gmid_graphs)
        self.nmos_data_lineEdit.setObjectName("nmos_data_lineEdit")
        self.horizontalLayout_7.addWidget(self.nmos_data_lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.nmos_data_browse_button = QtWidgets.QPushButton(self.gmid_graphs)
        self.nmos_data_browse_button.setObjectName("nmos_data_browse_button")
        self.horizontalLayout_7.addWidget(self.nmos_data_browse_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pmos_data_label = QtWidgets.QLabel(self.gmid_graphs)
        self.pmos_data_label.setObjectName("pmos_data_label")
        self.horizontalLayout_8.addWidget(self.pmos_data_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.pmos_data_lineEdit = QtWidgets.QLineEdit(self.gmid_graphs)
        self.pmos_data_lineEdit.setObjectName("pmos_data_lineEdit")
        self.horizontalLayout_8.addWidget(self.pmos_data_lineEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.pmos_data_browse_button = QtWidgets.QPushButton(self.gmid_graphs)
        self.pmos_data_browse_button.setObjectName("pmos_data_browse_button")
        self.horizontalLayout_8.addWidget(self.pmos_data_browse_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Lengt_range_label = QtWidgets.QLabel(self.gmid_graphs)
        self.Lengt_range_label.setObjectName("Lengt_range_label")
        self.horizontalLayout_3.addWidget(self.Lengt_range_label)
        self.length_range_lineEdit = QtWidgets.QLineEdit(self.gmid_graphs)
        self.length_range_lineEdit.setObjectName("length_range_lineEdit")
        self.horizontalLayout_3.addWidget(self.length_range_lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.VDS_range_label = QtWidgets.QLabel(self.gmid_graphs)
        self.VDS_range_label.setObjectName("VDS_range_label")
        self.horizontalLayout_4.addWidget(self.VDS_range_label)
        spacerItem12 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.VDS_range_lineEdit = QtWidgets.QLineEdit(self.gmid_graphs)
        self.VDS_range_lineEdit.setObjectName("VDS_range_lineEdit")
        self.horizontalLayout_4.addWidget(self.VDS_range_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.VSB_range_label = QtWidgets.QLabel(self.gmid_graphs)
        self.VSB_range_label.setObjectName("VSB_range_label")
        self.horizontalLayout_5.addWidget(self.VSB_range_label)
        spacerItem14 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.VSB_range_lineEdit = QtWidgets.QLineEdit(self.gmid_graphs)
        self.VSB_range_lineEdit.setObjectName("VSB_range_lineEdit")
        self.horizontalLayout_5.addWidget(self.VSB_range_lineEdit)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.Launch_graph_window_button = QtWidgets.QPushButton(self.gmid_graphs)
        self.Launch_graph_window_button.setObjectName("Launch_graph_window_button")
        self.verticalLayout_4.addWidget(self.Launch_graph_window_button)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.mainTabWidget.addTab(self.gmid_graphs, "")
        self.ota_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ota_tab.sizePolicy().hasHeightForWidth())
        self.ota_tab.setSizePolicy(sizePolicy)
        self.ota_tab.setObjectName("ota_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.ota_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.ota_tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.ota_tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.ota_tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.ota_tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.ota_tab, "")
        self.horizontalLayout.addWidget(self.mainTabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.modelPathLineEdit, self.browseModelbutton)
        main_window.setTabOrder(self.browseModelbutton, self.generateVGSLineEdit)
        main_window.setTabOrder(self.generateVGSLineEdit, self.generateVDSlineEdit)
        main_window.setTabOrder(self.generateVDSlineEdit, self.generateVBSlineEdit)
        main_window.setTabOrder(self.generateVBSlineEdit, self.generateLlineEdit)
        main_window.setTabOrder(self.generateLlineEdit, self.Width_lineEdit)
        main_window.setTabOrder(self.Width_lineEdit, self.temp_lineEdit)
        main_window.setTabOrder(self.temp_lineEdit, self.generatepushButton)
        main_window.setTabOrder(self.generatepushButton, self.mainTabWidget)
        main_window.setTabOrder(self.mainTabWidget, self.nmos_data_lineEdit)
        main_window.setTabOrder(self.nmos_data_lineEdit, self.nmos_data_browse_button)
        main_window.setTabOrder(self.nmos_data_browse_button, self.pmos_data_lineEdit)
        main_window.setTabOrder(self.pmos_data_lineEdit, self.pmos_data_browse_button)
        main_window.setTabOrder(self.pmos_data_browse_button, self.length_range_lineEdit)
        main_window.setTabOrder(self.length_range_lineEdit, self.VDS_range_lineEdit)
        main_window.setTabOrder(self.VDS_range_lineEdit, self.VSB_range_lineEdit)
        main_window.setTabOrder(self.VSB_range_lineEdit, self.Launch_graph_window_button)
        main_window.setTabOrder(self.Launch_graph_window_button, self.pushButton)
        main_window.setTabOrder(self.pushButton, self.pushButton_2)
        main_window.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Analog Designer Toolbox"))
        self.model_path_label.setText(_translate("main_window", "Model Path"))
        self.browseModelbutton.setText(_translate("main_window", "Browse"))
        self.modelPathLineEdit.setPlaceholderText(_translate("main_window", "Choose model file path"))
        self.label.setText(_translate("main_window", "Choose Sweep Parameters"))
        self.label_6.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">Length</span></p></body></html>"))
        self.generateVBSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.temp_lineEdit.setPlaceholderText(_translate("main_window", "Default = 27 degrees Celsius"))
        self.generateVDSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.temp_label.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">Temperature</span></p></body></html>"))
        self.label_3.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">DS</span></p></body></html>"))
        self.label_2.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">GS</span></p></body></html>"))
        self.generateVGSLineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.label_4.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">SB</span></p></body></html>"))
        self.generateLlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default is 0.2 microns)"))
        self.Width_lineEdit.setPlaceholderText(_translate("main_window", "in microns (Default is 1 micron)"))
        self.width_label.setText(_translate("main_window", "<html><head/><body><p><span style=\" font-size:11pt;\">Width</span></p></body></html>"))
        self.generatepushButton.setText(_translate("main_window", "Generate"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.generateGmIdCharts), _translate("main_window", "generate gm/id Array"))
        self.label_5.setText(_translate("main_window", "Insert the paths of generated NMOS, PMOS and the model file in addition to the desired values of Length, VDS and VSB to plot at:"))
        self.label_8.setText(_translate("main_window", "Notes:"))
        self.label_9.setText(_translate("main_window", "1) The VGS range used is the one used to generate the gm/id charts."))
        self.label_10.setText(_translate("main_window", "2) If any of the given values is out of the range of the used ranges to generate the gm/id charts, the minimum and maximum allowed values will be used as a start and end points, respectively, of the desired range."))
        self.nmos_data_label.setText(_translate("main_window", "NMOS Data File Path:"))
        self.nmos_data_browse_button.setText(_translate("main_window", "Browse"))
        self.pmos_data_label.setText(_translate("main_window", "PMOS Data File Path:"))
        self.pmos_data_browse_button.setText(_translate("main_window", "Browse"))
        self.Lengt_range_label.setText(_translate("main_window", "Length Range:"))
        self.length_range_lineEdit.setPlaceholderText(_translate("main_window", "min:step:max or value1 value2 value3, etc... (Default is minimum used length in the generated charts)"))
        self.VDS_range_label.setText(_translate("main_window", "VDS Range:"))
        self.VDS_range_lineEdit.setPlaceholderText(_translate("main_window", "min:step:max or value1 value2 value3, etc... (Default is VDSmax/2)"))
        self.VSB_range_label.setText(_translate("main_window", "VSB Range:"))
        self.VSB_range_lineEdit.setPlaceholderText(_translate("main_window", "min:step:max or value1 value2 value3, etc... (Default is VSB = 0)"))
        self.Launch_graph_window_button.setText(_translate("main_window", "Launch Graph Window"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.gmid_graphs), _translate("main_window", "gm/id Graphs"))
        self.label_17.setText(_translate("main_window", "Select OTA Topolpgy"))
        self.pushButton.setText(_translate("main_window", "Differential Input Differential Output"))
        self.pushButton_2.setText(_translate("main_window", "Differential Input Single Ended Output"))
        self.pushButton_3.setText(_translate("main_window", "Single Ended Input Single Ended Output"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.ota_tab), _translate("main_window", "OTA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
