# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(867, 563)
        main_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.generateGmIdCharts = QtWidgets.QWidget()
        self.generateGmIdCharts.setObjectName("generateGmIdCharts")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.generateGmIdCharts)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.model_path_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.model_path_label.setObjectName("model_path_label")
        self.gridLayout_3.addWidget(self.model_path_label, 0, 0, 1, 1)
        self.ngspice_command_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.ngspice_command_label.setEnabled(True)
        self.ngspice_command_label.setObjectName("ngspice_command_label")
        self.gridLayout_3.addWidget(self.ngspice_command_label, 1, 0, 1, 1)
        self.modelPathLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.modelPathLineEdit.setEnabled(True)
        self.modelPathLineEdit.setClearButtonEnabled(False)
        self.modelPathLineEdit.setObjectName("modelPathLineEdit")
        self.gridLayout_3.addWidget(self.modelPathLineEdit, 0, 1, 1, 1)
        self.browseModelbutton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.browseModelbutton.setObjectName("browseModelbutton")
        self.gridLayout_3.addWidget(self.browseModelbutton, 0, 2, 1, 1)
        self.ngSpiceCommandLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.ngSpiceCommandLineEdit.setObjectName("ngSpiceCommandLineEdit")
        self.gridLayout_3.addWidget(self.ngSpiceCommandLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.generateVGSLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVGSLineEdit.sizePolicy().hasHeightForWidth())
        self.generateVGSLineEdit.setSizePolicy(sizePolicy)
        self.generateVGSLineEdit.setObjectName("generateVGSLineEdit")
        self.gridLayout_4.addWidget(self.generateVGSLineEdit, 0, 1, 1, 1)
        self.generateVDSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVDSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVDSlineEdit.setSizePolicy(sizePolicy)
        self.generateVDSlineEdit.setObjectName("generateVDSlineEdit")
        self.gridLayout_4.addWidget(self.generateVDSlineEdit, 1, 1, 1, 1)
        self.generateVBSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVBSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVBSlineEdit.setSizePolicy(sizePolicy)
        self.generateVBSlineEdit.setObjectName("generateVBSlineEdit")
        self.gridLayout_4.addWidget(self.generateVBSlineEdit, 2, 1, 1, 1)
        self.generateLlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.generateLlineEdit.setObjectName("generateLlineEdit")
        self.gridLayout_4.addWidget(self.generateLlineEdit, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_7 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 1)
        self.expectedSizelineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.expectedSizelineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.expectedSizelineEdit.setFont(font)
        self.expectedSizelineEdit.setObjectName("expectedSizelineEdit")
        self.gridLayout_12.addWidget(self.expectedSizelineEdit, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 3, 1, 1)
        self.generatepushButton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.generatepushButton.setObjectName("generatepushButton")
        self.gridLayout_12.addWidget(self.generatepushButton, 0, 2, 1, 1)
        self.logGenerateChartslabel = QtWidgets.QLabel(self.generateGmIdCharts)
        self.logGenerateChartslabel.setText("")
        self.logGenerateChartslabel.setObjectName("logGenerateChartslabel")
        self.gridLayout_12.addWidget(self.logGenerateChartslabel, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.mainTabWidget.addTab(self.generateGmIdCharts, "")
        self.plotGmIdCurves = QtWidgets.QWidget()
        self.plotGmIdCurves.setObjectName("plotGmIdCurves")
        self.plotGmIdwidget_1 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_1.setGeometry(QtCore.QRect(10, 60, 331, 201))
        self.plotGmIdwidget_1.setObjectName("plotGmIdwidget_1")
        self.label_13 = QtWidgets.QLabel(self.plotGmIdwidget_1)
        self.label_13.setGeometry(QtCore.QRect(230, 0, 100, 20))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.plotGmIdwidget_2 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_2.setGeometry(QtCore.QRect(370, 60, 331, 201))
        self.plotGmIdwidget_2.setObjectName("plotGmIdwidget_2")
        self.label_15 = QtWidgets.QLabel(self.plotGmIdwidget_2)
        self.label_15.setGeometry(QtCore.QRect(230, 0, 100, 20))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.plotGmIdwidget_3 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_3.setGeometry(QtCore.QRect(10, 320, 331, 201))
        self.plotGmIdwidget_3.setObjectName("plotGmIdwidget_3")
        self.label_14 = QtWidgets.QLabel(self.plotGmIdwidget_3)
        self.label_14.setGeometry(QtCore.QRect(230, 0, 100, 20))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.plotGmIdwidget_4 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_4.setGeometry(QtCore.QRect(370, 320, 331, 201))
        self.plotGmIdwidget_4.setObjectName("plotGmIdwidget_4")
        self.label_16 = QtWidgets.QLabel(self.plotGmIdwidget_4)
        self.label_16.setGeometry(QtCore.QRect(230, 0, 100, 20))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.plotGmIdComboBox1_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_3.setGeometry(QtCore.QRect(214, 280, 69, 22))
        self.plotGmIdComboBox1_3.setObjectName("plotGmIdComboBox1_3")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 31, 21))
        self.label_5.setObjectName("label_5")
        self.plotGmIdComboBox1_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_2.setGeometry(QtCore.QRect(130, 280, 69, 22))
        self.plotGmIdComboBox1_2.setObjectName("plotGmIdComboBox1_2")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox2_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_2.setGeometry(QtCore.QRect(476, 280, 69, 22))
        self.plotGmIdComboBox2_2.setObjectName("plotGmIdComboBox2_2")
        self.plotGmIdComboBox2_2.addItem("")
        self.plotGmIdComboBox2_2.addItem("")
        self.plotGmIdComboBox2_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_8.setGeometry(QtCore.QRect(376, 280, 31, 21))
        self.label_8.setObjectName("label_8")
        self.plotGmIdComboBox2_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_1.setGeometry(QtCore.QRect(406, 280, 53, 22))
        self.plotGmIdComboBox2_1.setObjectName("plotGmIdComboBox2_1")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_3.setGeometry(QtCore.QRect(560, 280, 69, 22))
        self.plotGmIdComboBox2_3.setObjectName("plotGmIdComboBox2_3")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox3_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_2.setGeometry(QtCore.QRect(126, 540, 69, 22))
        self.plotGmIdComboBox3_2.setObjectName("plotGmIdComboBox3_2")
        self.plotGmIdComboBox3_2.addItem("")
        self.plotGmIdComboBox3_2.addItem("")
        self.plotGmIdComboBox3_2.addItem("")
        self.label_9 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_9.setGeometry(QtCore.QRect(26, 540, 31, 21))
        self.label_9.setObjectName("label_9")
        self.plotGmIdComboBox3_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_1.setGeometry(QtCore.QRect(56, 540, 53, 22))
        self.plotGmIdComboBox3_1.setObjectName("plotGmIdComboBox3_1")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_3.setGeometry(QtCore.QRect(210, 540, 69, 22))
        self.plotGmIdComboBox3_3.setObjectName("plotGmIdComboBox3_3")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox4_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_2.setGeometry(QtCore.QRect(476, 540, 69, 22))
        self.plotGmIdComboBox4_2.setObjectName("plotGmIdComboBox4_2")
        self.plotGmIdComboBox4_2.addItem("")
        self.plotGmIdComboBox4_2.addItem("")
        self.plotGmIdComboBox4_2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_10.setGeometry(QtCore.QRect(376, 540, 31, 21))
        self.label_10.setObjectName("label_10")
        self.plotGmIdComboBox4_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_1.setGeometry(QtCore.QRect(406, 540, 53, 22))
        self.plotGmIdComboBox4_1.setObjectName("plotGmIdComboBox4_1")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_3.setGeometry(QtCore.QRect(560, 540, 69, 22))
        self.plotGmIdComboBox4_3.setObjectName("plotGmIdComboBox4_3")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.LoaDataPlotlineEdit = QtWidgets.QLineEdit(self.plotGmIdCurves)
        self.LoaDataPlotlineEdit.setGeometry(QtCore.QRect(90, 10, 301, 20))
        self.LoaDataPlotlineEdit.setObjectName("LoaDataPlotlineEdit")
        self.label_11 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 51, 16))
        self.label_11.setObjectName("label_11")
        self.browseDataPlotbutton = QtWidgets.QPushButton(self.plotGmIdCurves)
        self.browseDataPlotbutton.setGeometry(QtCore.QRect(400, 10, 75, 23))
        self.browseDataPlotbutton.setObjectName("browseDataPlotbutton")
        self.label_12 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_12.setObjectName("label_12")
        self.LRangPlot = QtWidgets.QLineEdit(self.plotGmIdCurves)
        self.LRangPlot.setGeometry(QtCore.QRect(90, 40, 301, 20))
        self.LRangPlot.setObjectName("LRangPlot")
        self.plotGmIdComboBox1_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_1.setGeometry(QtCore.QRect(60, 280, 53, 22))
        self.plotGmIdComboBox1_1.setObjectName("plotGmIdComboBox1_1")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.mainTabWidget.addTab(self.plotGmIdCurves, "")
        self.horizontalLayout.addWidget(self.mainTabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.modelPathLineEdit, self.ngSpiceCommandLineEdit)
        main_window.setTabOrder(self.ngSpiceCommandLineEdit, self.generateVGSLineEdit)
        main_window.setTabOrder(self.generateVGSLineEdit, self.generateVDSlineEdit)
        main_window.setTabOrder(self.generateVDSlineEdit, self.generateVBSlineEdit)
        main_window.setTabOrder(self.generateVBSlineEdit, self.generateLlineEdit)
        main_window.setTabOrder(self.generateLlineEdit, self.browseModelbutton)
        main_window.setTabOrder(self.browseModelbutton, self.generatepushButton)
        main_window.setTabOrder(self.generatepushButton, self.expectedSizelineEdit)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "NG-Spice GUI"))
        self.model_path_label.setText(_translate("main_window", "Model Path"))
        self.ngspice_command_label.setText(_translate("main_window", "NG-Spice command"))
        self.modelPathLineEdit.setPlaceholderText(_translate("main_window", "Choose Model File Path"))
        self.browseModelbutton.setText(_translate("main_window", "Browse"))
        self.ngSpiceCommandLineEdit.setPlaceholderText(_translate("main_window", "Enter NG-Spice Command or Path"))
        self.label.setText(_translate("main_window", "Choose Sweep Parameters"))
        self.label_3.setText(_translate("main_window", "VDS"))
        self.label_6.setText(_translate("main_window", " L"))
        self.label_2.setText(_translate("main_window", "VGS"))
        self.label_4.setText(_translate("main_window", "VBS"))
        self.generateVGSLineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateVDSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateVBSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateLlineEdit.setPlaceholderText(_translate("main_window", "min1:step1:max1 min2:step2:max2 min3:step3:max3"))
        self.label_7.setText(_translate("main_window", "Expected Size"))
        self.generatepushButton.setText(_translate("main_window", "Generate"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.generateGmIdCharts), _translate("main_window", "Generate GmId Charts"))
        self.plotGmIdComboBox1_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox1_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox1_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox1_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox1_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox1_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox1_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox1_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox1_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox1_3.setItemText(10, _translate("main_window", "W"))
        self.label_5.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox1_2.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox1_2.setItemText(2, _translate("main_window", "*"))
        self.plotGmIdComboBox2_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox2_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox2_2.setItemText(2, _translate("main_window", "*"))
        self.label_8.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox2_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox2_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox2_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox2_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox2_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox2_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox2_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox2_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox2_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox2_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox2_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox2_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox2_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox2_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox2_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox2_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox2_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox2_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox2_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox2_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox2_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox2_3.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox3_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox3_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox3_2.setItemText(2, _translate("main_window", "*"))
        self.label_9.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox3_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox3_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox3_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox3_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox3_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox3_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox3_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox3_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox3_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox3_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox3_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox3_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox3_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox3_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox3_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox3_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox3_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox3_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox3_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox3_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox3_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox3_3.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox4_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox4_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox4_2.setItemText(2, _translate("main_window", "*"))
        self.label_10.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox4_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox4_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox4_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox4_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox4_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox4_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox4_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox4_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox4_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox4_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox4_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox4_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox4_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox4_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox4_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox4_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox4_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox4_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox4_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox4_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox4_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox4_3.setItemText(10, _translate("main_window", "W"))
        self.LoaDataPlotlineEdit.setPlaceholderText(_translate("main_window", "Path Of MOSFET Data File "))
        self.label_11.setText(_translate("main_window", "Load Data"))
        self.browseDataPlotbutton.setText(_translate("main_window", "Browse"))
        self.label_12.setText(_translate("main_window", "L Range"))
        self.LRangPlot.setPlaceholderText(_translate("main_window", "min1:step1:max1 min2:step2:max2 min3:step3:max3"))
        self.plotGmIdComboBox1_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox1_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox1_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox1_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox1_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox1_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox1_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox1_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox1_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox1_1.setItemText(10, _translate("main_window", "W"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.plotGmIdCurves), _translate("main_window", "Plot GmId Curves"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
