# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(814, 702)
        main_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.generateGmIdCharts = QtWidgets.QWidget()
        self.generateGmIdCharts.setObjectName("generateGmIdCharts")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.generateGmIdCharts)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.model_path_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.model_path_label.setObjectName("model_path_label")
        self.gridLayout_3.addWidget(self.model_path_label, 0, 0, 1, 1)
        self.ngspice_command_label = QtWidgets.QLabel(self.generateGmIdCharts)
        self.ngspice_command_label.setEnabled(True)
        self.ngspice_command_label.setObjectName("ngspice_command_label")
        self.gridLayout_3.addWidget(self.ngspice_command_label, 1, 0, 1, 1)
        self.modelPathLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.modelPathLineEdit.setEnabled(True)
        self.modelPathLineEdit.setClearButtonEnabled(False)
        self.modelPathLineEdit.setObjectName("modelPathLineEdit")
        self.gridLayout_3.addWidget(self.modelPathLineEdit, 0, 1, 1, 1)
        self.browseModelbutton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.browseModelbutton.setObjectName("browseModelbutton")
        self.gridLayout_3.addWidget(self.browseModelbutton, 0, 2, 1, 1)
        self.ngSpiceCommandLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.ngSpiceCommandLineEdit.setObjectName("ngSpiceCommandLineEdit")
        self.gridLayout_3.addWidget(self.ngSpiceCommandLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label = QtWidgets.QLabel(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.generateVGSLineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVGSLineEdit.sizePolicy().hasHeightForWidth())
        self.generateVGSLineEdit.setSizePolicy(sizePolicy)
        self.generateVGSLineEdit.setObjectName("generateVGSLineEdit")
        self.gridLayout_4.addWidget(self.generateVGSLineEdit, 0, 1, 1, 1)
        self.generateVDSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVDSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVDSlineEdit.setSizePolicy(sizePolicy)
        self.generateVDSlineEdit.setObjectName("generateVDSlineEdit")
        self.gridLayout_4.addWidget(self.generateVDSlineEdit, 1, 1, 1, 1)
        self.generateVBSlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateVBSlineEdit.sizePolicy().hasHeightForWidth())
        self.generateVBSlineEdit.setSizePolicy(sizePolicy)
        self.generateVBSlineEdit.setObjectName("generateVBSlineEdit")
        self.gridLayout_4.addWidget(self.generateVBSlineEdit, 2, 1, 1, 1)
        self.generateLlineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.generateLlineEdit.setObjectName("generateLlineEdit")
        self.gridLayout_4.addWidget(self.generateLlineEdit, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_7 = QtWidgets.QLabel(self.generateGmIdCharts)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 1)
        self.expectedSizelineEdit = QtWidgets.QLineEdit(self.generateGmIdCharts)
        self.expectedSizelineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.expectedSizelineEdit.setFont(font)
        self.expectedSizelineEdit.setObjectName("expectedSizelineEdit")
        self.gridLayout_12.addWidget(self.expectedSizelineEdit, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 3, 1, 1)
        self.logGenerateChartslabel = QtWidgets.QLabel(self.generateGmIdCharts)
        self.logGenerateChartslabel.setText("")
        self.logGenerateChartslabel.setObjectName("logGenerateChartslabel")
        self.gridLayout_12.addWidget(self.logGenerateChartslabel, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.generatepushButton = QtWidgets.QPushButton(self.generateGmIdCharts)
        self.generatepushButton.setObjectName("generatepushButton")
        self.gridLayout_2.addWidget(self.generatepushButton, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.generateGmIdCharts, "")
        self.plotGmIdCurves = QtWidgets.QWidget()
        self.plotGmIdCurves.setObjectName("plotGmIdCurves")
        self.plotGmIdwidget_1 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_1.setGeometry(QtCore.QRect(10, 60, 331, 201))
        self.plotGmIdwidget_1.setObjectName("plotGmIdwidget_1")
        self.label_13 = QtWidgets.QLabel(self.plotGmIdwidget_1)
        self.label_13.setGeometry(QtCore.QRect(240, 0, 81, 20))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.plotGmIdwidget_2 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_2.setGeometry(QtCore.QRect(370, 60, 331, 201))
        self.plotGmIdwidget_2.setObjectName("plotGmIdwidget_2")
        self.label_15 = QtWidgets.QLabel(self.plotGmIdwidget_2)
        self.label_15.setGeometry(QtCore.QRect(246, 0, 81, 20))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.plotGmIdwidget_3 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_3.setGeometry(QtCore.QRect(10, 320, 331, 201))
        self.plotGmIdwidget_3.setObjectName("plotGmIdwidget_3")
        self.label_14 = QtWidgets.QLabel(self.plotGmIdwidget_3)
        self.label_14.setGeometry(QtCore.QRect(240, 0, 91, 20))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.plotGmIdwidget_4 = PlotWidget(self.plotGmIdCurves)
        self.plotGmIdwidget_4.setGeometry(QtCore.QRect(370, 320, 331, 201))
        self.plotGmIdwidget_4.setObjectName("plotGmIdwidget_4")
        self.label_16 = QtWidgets.QLabel(self.plotGmIdwidget_4)
        self.label_16.setGeometry(QtCore.QRect(240, 0, 81, 20))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.plotGmIdComboBox1_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_3.setGeometry(QtCore.QRect(214, 280, 69, 22))
        self.plotGmIdComboBox1_3.setObjectName("plotGmIdComboBox1_3")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.plotGmIdComboBox1_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 31, 21))
        self.label_5.setObjectName("label_5")
        self.plotGmIdComboBox1_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_2.setGeometry(QtCore.QRect(130, 280, 69, 22))
        self.plotGmIdComboBox1_2.setObjectName("plotGmIdComboBox1_2")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox1_2.addItem("")
        self.plotGmIdComboBox2_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_2.setGeometry(QtCore.QRect(476, 280, 69, 22))
        self.plotGmIdComboBox2_2.setObjectName("plotGmIdComboBox2_2")
        self.plotGmIdComboBox2_2.addItem("")
        self.plotGmIdComboBox2_2.addItem("")
        self.plotGmIdComboBox2_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_8.setGeometry(QtCore.QRect(376, 280, 31, 21))
        self.label_8.setObjectName("label_8")
        self.plotGmIdComboBox2_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_1.setGeometry(QtCore.QRect(406, 280, 53, 22))
        self.plotGmIdComboBox2_1.setObjectName("plotGmIdComboBox2_1")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_1.addItem("")
        self.plotGmIdComboBox2_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox2_3.setGeometry(QtCore.QRect(560, 280, 69, 22))
        self.plotGmIdComboBox2_3.setObjectName("plotGmIdComboBox2_3")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox2_3.addItem("")
        self.plotGmIdComboBox3_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_2.setGeometry(QtCore.QRect(126, 540, 69, 22))
        self.plotGmIdComboBox3_2.setObjectName("plotGmIdComboBox3_2")
        self.plotGmIdComboBox3_2.addItem("")
        self.plotGmIdComboBox3_2.addItem("")
        self.plotGmIdComboBox3_2.addItem("")
        self.label_9 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_9.setGeometry(QtCore.QRect(26, 540, 31, 21))
        self.label_9.setObjectName("label_9")
        self.plotGmIdComboBox3_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_1.setGeometry(QtCore.QRect(56, 540, 53, 22))
        self.plotGmIdComboBox3_1.setObjectName("plotGmIdComboBox3_1")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_1.addItem("")
        self.plotGmIdComboBox3_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox3_3.setGeometry(QtCore.QRect(210, 540, 69, 22))
        self.plotGmIdComboBox3_3.setObjectName("plotGmIdComboBox3_3")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox3_3.addItem("")
        self.plotGmIdComboBox4_2 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_2.setGeometry(QtCore.QRect(476, 540, 69, 22))
        self.plotGmIdComboBox4_2.setObjectName("plotGmIdComboBox4_2")
        self.plotGmIdComboBox4_2.addItem("")
        self.plotGmIdComboBox4_2.addItem("")
        self.plotGmIdComboBox4_2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_10.setGeometry(QtCore.QRect(376, 540, 31, 21))
        self.label_10.setObjectName("label_10")
        self.plotGmIdComboBox4_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_1.setGeometry(QtCore.QRect(406, 540, 53, 22))
        self.plotGmIdComboBox4_1.setObjectName("plotGmIdComboBox4_1")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_1.addItem("")
        self.plotGmIdComboBox4_3 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox4_3.setGeometry(QtCore.QRect(560, 540, 69, 22))
        self.plotGmIdComboBox4_3.setObjectName("plotGmIdComboBox4_3")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.plotGmIdComboBox4_3.addItem("")
        self.LoaDataPlotlineEdit = QtWidgets.QLineEdit(self.plotGmIdCurves)
        self.LoaDataPlotlineEdit.setGeometry(QtCore.QRect(90, 10, 301, 20))
        self.LoaDataPlotlineEdit.setObjectName("LoaDataPlotlineEdit")
        self.label_11 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 51, 16))
        self.label_11.setObjectName("label_11")
        self.browseDataPlotbutton = QtWidgets.QPushButton(self.plotGmIdCurves)
        self.browseDataPlotbutton.setGeometry(QtCore.QRect(400, 10, 75, 23))
        self.browseDataPlotbutton.setObjectName("browseDataPlotbutton")
        self.label_12 = QtWidgets.QLabel(self.plotGmIdCurves)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_12.setObjectName("label_12")
        self.LRangPlot = QtWidgets.QLineEdit(self.plotGmIdCurves)
        self.LRangPlot.setGeometry(QtCore.QRect(90, 40, 301, 20))
        self.LRangPlot.setObjectName("LRangPlot")
        self.plotGmIdComboBox1_1 = QtWidgets.QComboBox(self.plotGmIdCurves)
        self.plotGmIdComboBox1_1.setGeometry(QtCore.QRect(60, 280, 53, 22))
        self.plotGmIdComboBox1_1.setObjectName("plotGmIdComboBox1_1")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.plotGmIdComboBox1_1.addItem("")
        self.mainTabWidget.addTab(self.plotGmIdCurves, "")
        self.ota_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ota_tab.sizePolicy().hasHeightForWidth())
        self.ota_tab.setSizePolicy(sizePolicy)
        self.ota_tab.setObjectName("ota_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.ota_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.OTA_image_label = QtWidgets.QLabel(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OTA_image_label.sizePolicy().hasHeightForWidth())
        self.OTA_image_label.setSizePolicy(sizePolicy)
        self.OTA_image_label.setText("")
        self.OTA_image_label.setPixmap(QtGui.QPixmap("C:/Users/Marawan/Desktop/ota.jpg"))
        self.OTA_image_label.setScaledContents(True)
        self.OTA_image_label.setObjectName("OTA_image_label")
        self.horizontalLayout_21.addWidget(self.OTA_image_label)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_21, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VDDLabel = QtWidgets.QLabel(self.ota_tab)
        self.VDDLabel.setObjectName("VDDLabel")
        self.horizontalLayout_3.addWidget(self.VDDLabel)
        spacerItem5 = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.ota_tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.VINCMLabel = QtWidgets.QLabel(self.ota_tab)
        self.VINCMLabel.setObjectName("VINCMLabel")
        self.horizontalLayout_5.addWidget(self.VINCMLabel)
        self.VINCM_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.VINCM_lineEdit.setObjectName("VINCM_lineEdit")
        self.horizontalLayout_5.addWidget(self.VINCM_lineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.VINDLabel = QtWidgets.QLabel(self.ota_tab)
        self.VINDLabel.setObjectName("VINDLabel")
        self.horizontalLayout_4.addWidget(self.VINDLabel)
        spacerItem8 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.VIND_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.VIND_lineEdit.setObjectName("VIND_lineEdit")
        self.horizontalLayout_4.addWidget(self.VIND_lineEdit)
        spacerItem10 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.M1BiasVoltageLabel = QtWidgets.QLabel(self.ota_tab)
        self.M1BiasVoltageLabel.setObjectName("M1BiasVoltageLabel")
        self.horizontalLayout_2.addWidget(self.M1BiasVoltageLabel)
        spacerItem11 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.M1_Bias_Voltage_LineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.M1_Bias_Voltage_LineEdit.setObjectName("M1_Bias_Voltage_LineEdit")
        self.horizontalLayout_2.addWidget(self.M1_Bias_Voltage_LineEdit)
        spacerItem12 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Start_freq_label = QtWidgets.QLabel(self.ota_tab)
        self.Start_freq_label.setObjectName("Start_freq_label")
        self.horizontalLayout_17.addWidget(self.Start_freq_label)
        spacerItem14 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.start_freq_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.start_freq_lineEdit.setObjectName("start_freq_lineEdit")
        self.horizontalLayout_17.addWidget(self.start_freq_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Stop_freq_label = QtWidgets.QLabel(self.ota_tab)
        self.Stop_freq_label.setObjectName("Stop_freq_label")
        self.horizontalLayout_22.addWidget(self.Stop_freq_label)
        spacerItem15 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem15)
        self.Stop_freq_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.Stop_freq_lineEdit.setObjectName("Stop_freq_lineEdit")
        self.horizontalLayout_22.addWidget(self.Stop_freq_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.no_poinrs_dec_label = QtWidgets.QLabel(self.ota_tab)
        self.no_poinrs_dec_label.setObjectName("no_poinrs_dec_label")
        self.horizontalLayout_24.addWidget(self.no_poinrs_dec_label)
        self.Points_dec_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.Points_dec_lineEdit.setObjectName("Points_dec_lineEdit")
        self.horizontalLayout_24.addWidget(self.Points_dec_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Transistors_length_Label = QtWidgets.QLabel(self.ota_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Transistors_length_Label.setFont(font)
        self.Transistors_length_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Transistors_length_Label.setObjectName("Transistors_length_Label")
        self.horizontalLayout_18.addWidget(self.Transistors_length_Label)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_M1_L = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_L.setObjectName("label_M1_L")
        self.horizontalLayout_11.addWidget(self.label_M1_L)
        self.M1_L_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M1_L_lineEdit.sizePolicy().hasHeightForWidth())
        self.M1_L_lineEdit.setSizePolicy(sizePolicy)
        self.M1_L_lineEdit.setObjectName("M1_L_lineEdit")
        self.horizontalLayout_11.addWidget(self.M1_L_lineEdit)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_M2_L = QtWidgets.QLabel(self.ota_tab)
        self.label_M2_L.setObjectName("label_M2_L")
        self.horizontalLayout_10.addWidget(self.label_M2_L)
        self.M2_L_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M2_L_lineEdit.sizePolicy().hasHeightForWidth())
        self.M2_L_lineEdit.setSizePolicy(sizePolicy)
        self.M2_L_lineEdit.setObjectName("M2_L_lineEdit")
        self.horizontalLayout_10.addWidget(self.M2_L_lineEdit)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_M3_L = QtWidgets.QLabel(self.ota_tab)
        self.label_M3_L.setObjectName("label_M3_L")
        self.horizontalLayout_9.addWidget(self.label_M3_L)
        self.M3_L_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M3_L_lineEdit.sizePolicy().hasHeightForWidth())
        self.M3_L_lineEdit.setSizePolicy(sizePolicy)
        self.M3_L_lineEdit.setObjectName("M3_L_lineEdit")
        self.horizontalLayout_9.addWidget(self.M3_L_lineEdit)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_M4_L = QtWidgets.QLabel(self.ota_tab)
        self.label_M4_L.setObjectName("label_M4_L")
        self.horizontalLayout_8.addWidget(self.label_M4_L)
        self.M4_L_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M4_L_lineEdit.sizePolicy().hasHeightForWidth())
        self.M4_L_lineEdit.setSizePolicy(sizePolicy)
        self.M4_L_lineEdit.setObjectName("M4_L_lineEdit")
        self.horizontalLayout_8.addWidget(self.M4_L_lineEdit)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_M5_L = QtWidgets.QLabel(self.ota_tab)
        self.label_M5_L.setObjectName("label_M5_L")
        self.horizontalLayout_7.addWidget(self.label_M5_L)
        self.M5_L_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M5_L_lineEdit.sizePolicy().hasHeightForWidth())
        self.M5_L_lineEdit.setSizePolicy(sizePolicy)
        self.M5_L_lineEdit.setObjectName("M5_L_lineEdit")
        self.horizontalLayout_7.addWidget(self.M5_L_lineEdit)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Transistors_Width_Label = QtWidgets.QLabel(self.ota_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Transistors_Width_Label.setFont(font)
        self.Transistors_Width_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Transistors_Width_Label.setObjectName("Transistors_Width_Label")
        self.horizontalLayout_19.addWidget(self.Transistors_Width_Label)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_M1_W = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_W.setObjectName("label_M1_W")
        self.horizontalLayout_16.addWidget(self.label_M1_W)
        self.M1_W_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.M1_W_lineEdit.setObjectName("M1_W_lineEdit")
        self.horizontalLayout_16.addWidget(self.M1_W_lineEdit)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem24)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_M1_W_2 = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_W_2.setObjectName("label_M1_W_2")
        self.horizontalLayout_15.addWidget(self.label_M1_W_2)
        self.M2_W_lineEdit = QtWidgets.QLineEdit(self.ota_tab)
        self.M2_W_lineEdit.setObjectName("M2_W_lineEdit")
        self.horizontalLayout_15.addWidget(self.M2_W_lineEdit)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_M1_W_3 = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_W_3.setObjectName("label_M1_W_3")
        self.horizontalLayout_14.addWidget(self.label_M1_W_3)
        self.M3_W_lineEdit_3 = QtWidgets.QLineEdit(self.ota_tab)
        self.M3_W_lineEdit_3.setObjectName("M3_W_lineEdit_3")
        self.horizontalLayout_14.addWidget(self.M3_W_lineEdit_3)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_M1_W_4 = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_W_4.setObjectName("label_M1_W_4")
        self.horizontalLayout_13.addWidget(self.label_M1_W_4)
        self.M4_W_lineEdit_4 = QtWidgets.QLineEdit(self.ota_tab)
        self.M4_W_lineEdit_4.setObjectName("M4_W_lineEdit_4")
        self.horizontalLayout_13.addWidget(self.M4_W_lineEdit_4)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem27)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_M1_W_5 = QtWidgets.QLabel(self.ota_tab)
        self.label_M1_W_5.setObjectName("label_M1_W_5")
        self.horizontalLayout_12.addWidget(self.label_M1_W_5)
        self.M5_W_lineEdit_5 = QtWidgets.QLineEdit(self.ota_tab)
        self.M5_W_lineEdit_5.setObjectName("M5_W_lineEdit_5")
        self.horizontalLayout_12.addWidget(self.M5_W_lineEdit_5)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem28)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem29 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem29)
        self.gridLayout.addLayout(self.horizontalLayout_23, 0, 1, 1, 1)
        self.mainTabWidget.addTab(self.ota_tab, "")
        self.horizontalLayout.addWidget(self.mainTabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.horizontalLayout_20.addItem(spacerItem30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem31)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Results_Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Results_Label.setFont(font)
        self.Results_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Results_Label.setObjectName("Results_Label")
        self.verticalLayout_9.addWidget(self.Results_Label)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Gain_label = QtWidgets.QLabel(self.centralwidget)
        self.Gain_label.setObjectName("Gain_label")
        self.horizontalLayout_27.addWidget(self.Gain_label)
        self.Gain_Result_label = QtWidgets.QLabel(self.centralwidget)
        self.Gain_Result_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Gain_Result_label.setText("")
        self.Gain_Result_label.setObjectName("Gain_Result_label")
        self.horizontalLayout_27.addWidget(self.Gain_Result_label)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Bandwidth_label = QtWidgets.QLabel(self.centralwidget)
        self.Bandwidth_label.setObjectName("Bandwidth_label")
        self.horizontalLayout_26.addWidget(self.Bandwidth_label)
        self.Bandwidth_result_label = QtWidgets.QLabel(self.centralwidget)
        self.Bandwidth_result_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Bandwidth_result_label.setText("")
        self.Bandwidth_result_label.setObjectName("Bandwidth_result_label")
        self.horizontalLayout_26.addWidget(self.Bandwidth_result_label)
        self.verticalLayout_9.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.UGF_label = QtWidgets.QLabel(self.centralwidget)
        self.UGF_label.setObjectName("UGF_label")
        self.horizontalLayout_25.addWidget(self.UGF_label)
        self.UGF_result_label = QtWidgets.QLabel(self.centralwidget)
        self.UGF_result_label.setFrameShape(QtWidgets.QFrame.Box)
        self.UGF_result_label.setText("")
        self.UGF_result_label.setObjectName("UGF_result_label")
        self.horizontalLayout_25.addWidget(self.UGF_result_label)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.verticalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.mainTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.modelPathLineEdit, self.ngSpiceCommandLineEdit)
        main_window.setTabOrder(self.ngSpiceCommandLineEdit, self.generateVGSLineEdit)
        main_window.setTabOrder(self.generateVGSLineEdit, self.generateVDSlineEdit)
        main_window.setTabOrder(self.generateVDSlineEdit, self.generateVBSlineEdit)
        main_window.setTabOrder(self.generateVBSlineEdit, self.generateLlineEdit)
        main_window.setTabOrder(self.generateLlineEdit, self.browseModelbutton)
        main_window.setTabOrder(self.browseModelbutton, self.expectedSizelineEdit)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.model_path_label.setText(_translate("main_window", "Model Path"))
        self.ngspice_command_label.setText(_translate("main_window", "ngSpice command"))
        self.modelPathLineEdit.setPlaceholderText(_translate("main_window", "Choose Model File Path"))
        self.browseModelbutton.setText(_translate("main_window", "Browse"))
        self.ngSpiceCommandLineEdit.setPlaceholderText(_translate("main_window", "Enter NG-Spics Command or Path"))
        self.label.setText(_translate("main_window", "Choose Sweep Parameters"))
        self.label_3.setText(_translate("main_window", "VDS"))
        self.label_6.setText(_translate("main_window", " L"))
        self.label_2.setText(_translate("main_window", "VGS"))
        self.label_4.setText(_translate("main_window", "VBS"))
        self.generateVGSLineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateVDSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateVBSlineEdit.setPlaceholderText(_translate("main_window", "min:step:max (Default 0:0.1:1)"))
        self.generateLlineEdit.setPlaceholderText(_translate("main_window", "min1:step1:max1 min2:step2:max2 min3:step3:max3"))
        self.label_7.setText(_translate("main_window", "Expected Size"))
        self.generatepushButton.setText(_translate("main_window", "Generate"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.generateGmIdCharts), _translate("main_window", "Generate GmId Charts"))
        self.plotGmIdComboBox1_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox1_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox1_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox1_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox1_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox1_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox1_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox1_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox1_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox1_3.setItemText(10, _translate("main_window", "W"))
        self.label_5.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox1_2.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox1_2.setItemText(2, _translate("main_window", "*"))
        self.plotGmIdComboBox2_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox2_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox2_2.setItemText(2, _translate("main_window", "*"))
        self.label_8.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox2_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox2_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox2_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox2_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox2_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox2_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox2_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox2_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox2_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox2_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox2_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox2_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox2_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox2_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox2_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox2_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox2_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox2_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox2_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox2_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox2_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox2_3.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox3_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox3_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox3_2.setItemText(2, _translate("main_window", "*"))
        self.label_9.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox3_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox3_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox3_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox3_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox3_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox3_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox3_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox3_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox3_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox3_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox3_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox3_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox3_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox3_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox3_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox3_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox3_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox3_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox3_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox3_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox3_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox3_3.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox4_2.setItemText(0, _translate("main_window", "-----"))
        self.plotGmIdComboBox4_2.setItemText(1, _translate("main_window", "/"))
        self.plotGmIdComboBox4_2.setItemText(2, _translate("main_window", "*"))
        self.label_10.setText(_translate("main_window", "Plot"))
        self.plotGmIdComboBox4_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox4_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox4_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox4_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox4_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox4_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox4_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox4_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox4_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox4_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox4_1.setItemText(10, _translate("main_window", "W"))
        self.plotGmIdComboBox4_3.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox4_3.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox4_3.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox4_3.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox4_3.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox4_3.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox4_3.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox4_3.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox4_3.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox4_3.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox4_3.setItemText(10, _translate("main_window", "W"))
        self.LoaDataPlotlineEdit.setPlaceholderText(_translate("main_window", "Path Of MOSFET Data File "))
        self.label_11.setText(_translate("main_window", "Load Data"))
        self.browseDataPlotbutton.setText(_translate("main_window", "Browse"))
        self.label_12.setText(_translate("main_window", "L Range"))
        self.LRangPlot.setPlaceholderText(_translate("main_window", "mn1:st1:mx1 mn2:st2:mx2 mn3:st3:mx3"))
        self.plotGmIdComboBox1_1.setItemText(0, _translate("main_window", "------"))
        self.plotGmIdComboBox1_1.setItemText(1, _translate("main_window", "ID"))
        self.plotGmIdComboBox1_1.setItemText(2, _translate("main_window", "GM"))
        self.plotGmIdComboBox1_1.setItemText(3, _translate("main_window", "GMBS"))
        self.plotGmIdComboBox1_1.setItemText(4, _translate("main_window", "GDS"))
        self.plotGmIdComboBox1_1.setItemText(5, _translate("main_window", "CGG"))
        self.plotGmIdComboBox1_1.setItemText(6, _translate("main_window", "CGS"))
        self.plotGmIdComboBox1_1.setItemText(7, _translate("main_window", "CGD"))
        self.plotGmIdComboBox1_1.setItemText(8, _translate("main_window", "CDD"))
        self.plotGmIdComboBox1_1.setItemText(9, _translate("main_window", "CBS"))
        self.plotGmIdComboBox1_1.setItemText(10, _translate("main_window", "W"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.plotGmIdCurves), _translate("main_window", "Plot GmId Curves"))
        self.VDDLabel.setText(_translate("main_window", "VDD Value"))
        self.VINCMLabel.setText(_translate("main_window", "Input Common Mode Voltage"))
        self.VINDLabel.setText(_translate("main_window", "Input Differential Voltage"))
        self.M1BiasVoltageLabel.setText(_translate("main_window", "M1 Bias Voltage"))
        self.Start_freq_label.setText(_translate("main_window", "Start Frequency"))
        self.Stop_freq_label.setText(_translate("main_window", "Stop Frequency"))
        self.no_poinrs_dec_label.setText(_translate("main_window", "Number of Points per Decade"))
        self.Transistors_length_Label.setText(_translate("main_window", "Length of Transistors"))
        self.label_M1_L.setText(_translate("main_window", "Length of M1"))
        self.label_M2_L.setText(_translate("main_window", "Length of M2"))
        self.label_M3_L.setText(_translate("main_window", "Length of M3"))
        self.label_M4_L.setText(_translate("main_window", "Length of M4"))
        self.label_M5_L.setText(_translate("main_window", "Length of M5"))
        self.Transistors_Width_Label.setText(_translate("main_window", "Width  of Transistors"))
        self.label_M1_W.setText(_translate("main_window", "Width of M1"))
        self.label_M1_W_2.setText(_translate("main_window", "Width of M2"))
        self.label_M1_W_3.setText(_translate("main_window", "Width of M3"))
        self.label_M1_W_4.setText(_translate("main_window", "Width of M4"))
        self.label_M1_W_5.setText(_translate("main_window", "Width of M5"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.ota_tab), _translate("main_window", "5T-OTA"))
        self.pushButton.setText(_translate("main_window", "Plot"))
        self.Results_Label.setText(_translate("main_window", "Results"))
        self.Gain_label.setText(_translate("main_window", "Gain"))
        self.Bandwidth_label.setText(_translate("main_window", "Bandwidth"))
        self.UGF_label.setText(_translate("main_window", "Unity Gain Frequency"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
